// Runs during the Netlify build (see netlify.toml -> [build].command).
// Reads SUPABASE_URL and SUPABASE_ANON_KEY from the Netlify environment
// (Site settings > Environment variables) and writes them into a small
// static file the browser can load with a plain <script> tag.
//
// This keeps the app 100% static (no bundler) while still honoring the
// "use environment variables for Supabase URL / anon key" requirement.

const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';

if (!url || !anonKey) {
  console.warn(
    '[generate-config] SUPABASE_URL / SUPABASE_ANON_KEY not set. ' +
    'The app will run in local-storage-only mode until they are configured.'
  );
}

const content = `// AUTO-GENERATED at build time by scripts/generate-config.js
// Do not edit this file by hand - it is overwritten on every deploy.
window.__SUPABASE_CONFIG__ = {
  url: ${JSON.stringify(url)},
  anonKey: ${JSON.stringify(anonKey)}
};
`;

const outPath = path.join(__dirname, '..', 'public', 'js', 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`[generate-config] wrote ${outPath}`);
